### ISSUE TITLE
Colt fails on applying transformations to angularjs

### ISSUE THREAD

**Issue by webuniverseio** [code-orchestra/colt-sublime3-plugin#11]
Fails with following error for angular.js (not minified):

```
identifier is a reserved word (js/ng/angular.js#16141):
```

**Comment by makc** [comment]
we use [closure compiler](https://developers.google.com/closure/compiler/) (which in turn uses [rhino](https://github.com/mozilla/rhino/) fork) to parse javascript. if you are able to run closure compiler on angular without this syntax error, let us now, otherwise we will not be able to fix this.

however,

unless you actually need to work on angular source, you can exclude it from "live" preprocessing by adding it with "-" to source pattern list. let me know if this solves your problem.

**Comment by webuniverseio** [comment]
I'm fine with that, thank you

**Comment by webuniverseio** [comment]
Hi @makc, do you know if arguments is used by rhino as a keyword too? Check the image below:
![Arguments issue](http://clip2net.com/clip/m243817/1390758353-arguments-278kb.gif?nocache=1)

**Comment by makc** [comment]
we inject inner functions everywhere and call those when sublime plugin requires some expression value. "arguments" probably resolves to arguments of the function we inject.
